### ISSUE TITLE
Incorrect path of section.yaml

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment-flows#4]
After the recent commit for avoiding pass large objects between tasks, 52e8758bc02571138e78b2a318494eec6bf35178, a bug was introduced into the path of the section.yaml file.
This resulted in the updated section.yaml file being saved in a wrong folder. 
For example, in a folder of section number 17043, /path_to_experiment/sample_folder/s17043_g1, there are the old section.yaml file and the updated s17043_g1/section.yaml, which was stored in a sub-folder with the same folder name.

**Comment by tibuch** [comment]
Good catch, thanks! Working on a fix.
